'''
Problem Statement : Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.


URL : https://projecteuler.net/problem=2
'''

def fibList(num):
    fList = [1, 2]
    while fList[-1] < num:
        fList.append(fList[-2] + fList[-1])
    if fList[-1] >= num:
        return fList[:-1]
    return fList


fibL = fibList(4000000)
print sum([x for x in fibL if x % 2 == 0])